name: deploy-book

# Only run this when the gh-pages branch changes
on:
  push:
    branches:
    - main
    
# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # forget about trying to use a production branch, use the main
      # with:
         #name of the branch to build.  Only put things on this branch if they're 
         #ready for someone to look at it.
      #  ref: production 

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book clean .
        jupyter-book build .
    
    # Build Pdf via html
    #- name: Build the pdf via HTML
    #  run: |
    #    jupyter-book build ./ --builder pdfhtml
    #    mv ./_build/pdf/book.pdf ./_build/html/book-via-html.pdf
    
    # Build Pdf via latex
    #- name: Build the pdf via latex
    #  run: |
    #    sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex latexmk
    #    jupyter-book build ./ --builder pdflatex
    #    mv ./_build/latex/book.pdf ./_build/html/book-via-latex.pdf
        
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
